# -*- coding: utf-8 -*-
"""Group15_LabFInal_NTAD-usingRandomForest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbvjfAb6uwJxIAA1JCfcZAwVR7de0uOC

**Network Traffic Anomaly Detection** using ***Random Forest***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

df = pd.read_csv("/content/networkanomalydataset_augmented.csv")

print("First 5 Rows:")
display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nLabel Distribution:")
print(df["Label"].value_counts())

X = df.drop("Label", axis=1)
y = df["Label"]

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)

print("\nFeature Columns:")
print(X.columns.tolist())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Set:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nTesting Set:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print("\nTraining Label Distribution:")
print(y_train.value_counts())

print("\nTesting Label Distribution:")
print(y_test.value_counts())

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Random Forest model training completed.")

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Model Evaluation Results")
print("------------------------")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-Score : {f1:.4f}")

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Anomaly"]
))

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)


plt.figure(figsize=(6, 4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Normal", "Anomaly"],
    yticklabels=["Normal", "Anomaly"]
)

plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Random Forest Confusion Matrix")
plt.show()

# Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV, learning_curve

param_grid = {
    "n_estimators": [10, 25, 50, 100, 200],
    "max_depth": [2, 3, 4, 5, 6, 8, 10, 15, None],
}

print(f"\nThis grid will try {len(param_grid['n_estimators']) * len(param_grid['max_depth'])} combinations,")
print("each evaluated with 5-fold cross-validation.")

grid_search = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)
grid_search.fit(X_train, y_train)

best_n_estimators = grid_search.best_params_["n_estimators"]
best_max_depth = grid_search.best_params_["max_depth"]

print("\nBest parameters:", grid_search.best_params_)
print(f"Best cross-validated accuracy: {grid_search.best_score_:.4f}")

fixed_model = grid_search.best_estimator_
fixed_pred = fixed_model.predict(X_test)

print(f"\nFinal Model Evaluation (n_estimators = {best_n_estimators}, max_depth = {best_max_depth})")
print("-----------------------------------------------------------------")
print(f"Accuracy : {accuracy_score(y_test, fixed_pred):.4f}")
print(f"Precision: {precision_score(y_test, fixed_pred):.4f}")
print(f"Recall   : {recall_score(y_test, fixed_pred):.4f}")
print(f"F1-Score : {f1_score(y_test, fixed_pred):.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, fixed_pred))

learning_curve_configs = [
    ("Before Tuning (default: max_depth = None)", RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)),
    (f"After GridSearchCV (n_estimators={best_n_estimators}, max_depth={best_max_depth})", fixed_model),
]

fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))
gaps_summary = []

for ax, (title, lc_model) in zip(axes, learning_curve_configs):
    lc_train_sizes, lc_train_scores, lc_val_scores = learning_curve(
        lc_model, X_train, y_train, train_sizes=np.linspace(0.1, 1.0, 10),
        cv=5, scoring="accuracy", random_state=42
    )
    lc_train_mean = lc_train_scores.mean(axis=1)
    lc_val_mean = lc_val_scores.mean(axis=1)
    lc_gap = lc_train_mean[-1] - lc_val_mean[-1]
    gaps_summary.append((title, lc_gap))

    ax.plot(lc_train_sizes, lc_train_mean, "o-", color="#2E5A8C", label="Training accuracy")
    ax.plot(lc_train_sizes, lc_val_mean, "o-", color="#C44E52", label="Cross-validation accuracy")
    ax.set_xlabel("Number of Training Samples")
    ax.set_ylabel("Accuracy")
    ax.set_title(f"{title}\nFinal gap = {lc_gap:.4f}", fontsize=10)
    ax.legend(loc="lower right")
    ax.grid(alpha=0.3)
    ax.set_ylim(0.84, 1.01)

plt.suptitle("Learning Curve Before vs. After GridSearchCV Tuning", fontsize=13)
plt.tight_layout()
plt.show()

print("\nLearning Curve Gap Summary")
print("----------------------------")
for title, gap in gaps_summary:
    print(f"{title}: gap = {gap:.4f}")
print(f"\nThe gap shrank by {gaps_summary[0][1] - gaps_summary[1][1]:.4f} after GridSearchCV tuning.")
print("A smaller gap means training performance and real-world (cross-validation)")
print("performance are now much closer in agreement, which is the visual signature")
print("of a well-fitted model rather than an overfit one.")

# Decision Boundary Visualization
feat_x = "Inbound Rate(bit/s)"
feat_y = "Inbound Bandwidth Utilization(%)"
X2 = df[[feat_x, feat_y]].values
y2 = df["Label"].values

X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.20, random_state=42, stratify=y2
)

model2d = RandomForestClassifier(n_estimators=best_n_estimators, max_depth=best_max_depth, random_state=42)
model2d.fit(X2_train, y2_train)

x_min, x_max = X2[:, 0].min() - 0.5, X2[:, 0].max() + 0.5
y_min, y_max = X2[:, 1].min() - 0.5, X2[:, 1].max() + 0.5
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 400), np.linspace(y_min, y_max, 400))

# Use predicted probability of class 1 (Anomaly) instead of hard predictions,
# so a single boundary LINE can be drawn at the 0.5 probability threshold
proba = model2d.predict_proba(np.c_[xx.ravel(), yy.ravel()])[:, 1]
proba = proba.reshape(xx.shape)

plt.figure(figsize=(7, 6))
plt.contour(xx, yy, proba, levels=[0.5], colors="black", linewidths=2)
for label, color, name in [(0, "#2166AC", "Normal"), (1, "#B2182B", "Anomaly")]:
    mask = y2 == label
    plt.scatter(X2[mask, 0], X2[mask, 1], c=color, s=15, alpha=0.6, label=name, edgecolors="none")

plt.xlabel(feat_x)
plt.ylabel(feat_y)
plt.title(f"Random Forest Decision Boundary (n_estimators = {best_n_estimators}, max_depth = {best_max_depth})")
plt.legend(loc="upper left")
plt.tight_layout()
plt.show()